---
name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_READONLY_TOKEN }}
      - name: Build container
        run: make
